version: "3"
services:

# Nginx Service
  nginx:
    image: nginx
    restart: always
    container_name: Nginx
    volumes:
      - ./www:/var/www/html # Public Folder holds the Web Application files
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf # Nginx Application Config File
      - ./docker/nginx/logs/access.log:/var/log/nginx/access.log # Access Log
      - ./docker/nginx/logs/error.log:/var/log/nginx/error.log # Error Log
    ports:
      - 80:80
      - 443:443
    links:
      - php

  # PHP Service - PHP-FPM 7.1
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    container_name: PHP-FPM7.1
    volumes:
      - ./www:/var/www/html # Public Folder holds the Web Application files for PHP-FPM access
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    expose:
      - 9000
    links:
      - database
      - redis
    environment:
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

  # MariaDB
  database:
    image: mariadb
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database-data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    ports:
      - 3306

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    links:
      - database

  redis:
    image: redis
    ports:
      - 6379

volumes:
  database-data:
    driver: local
